apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv2
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /path/to/your/exported/dir
    server: nfs-server.example.com
  claimRef:
    namespace: redis
    name: pvc-redis-replica
